version: '3.8'

services:
  eshop:
    image: nurulhadii/zentra-eshop:dev
    container_name: eshop_local
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=${NODE_ENV}
      - PORT=3001
      - API_URL=${API_URL}
      - ESHOP_URL=${ESHOP_URL}
      - PGADMIN_URL=${PGADMIN_URL}
    env_file:
      - .env.local

  postgres:
    image: postgres:15.4-alpine
    container_name: postgres_local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.local.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    env_file:
      - .env.local

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    depends_on:
      - postgres
    env_file:
      - .env.local

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: elasticsearch_local
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=zentra-local
      - network.host=0.0.0.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    env_file:
      - .env.local

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: kibana_local
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=${ELASTICSEARCH_HOSTS}
      - SERVER_NAME=localhost
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    env_file:
      - .env.local

volumes:
  postgres_data:
  elasticsearch_data: 