services:
  # Traefik reverse proxy
  traefik:
    image: traefik:v2.10
    container_name: traefik
    restart: always
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    command:
      - "--api.insecure=false"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=traefik-net"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.web.http.redirections.entryPoint.permanent=true"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.letsencrypt.acme.email=admin@badamigroups.com"
      - "--certificatesresolvers.letsencrypt.acme.storage=/etc/traefik/acme.json"
      - "--log.level=DEBUG"
      - "--accesslog=true"
      - "--accesslog.filepath=/var/log/traefik/access.log"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ${REMOTE_PATH}/traefik/acme.json:/etc/traefik/acme.json
      - ${REMOTE_PATH}/traefik/logs:/var/log/traefik
    networks:
      - traefik-net

  # Frontend Development
  frontend_dev:
    image: nurulhadii/zentra-ui:dev
    container_name: frontend_dev
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_URL=https://dev.zentra.badamigroups.com
      - ESHOP_URL=https://dev.eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.frontend-dev.rule=Host(`dev.bisnisqu.badamigroups.com`)"
      - "traefik.http.routers.frontend-dev.entrypoints=websecure"
      - "traefik.http.routers.frontend-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend-dev.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.frontend-dev-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend-dev.middlewares=frontend-dev-headers"
      - "traefik.http.services.frontend-dev.loadbalancer.server.scheme=http"
      - "traefik.http.services.frontend-dev.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.frontend-dev.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net

  # E-shop Development
  eshop_dev:
    image: nurulhadii/zentra-eshop:dev
    container_name: eshop_dev
    restart: always
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_URL=https://dev.zentra.badamigroups.com
      - ESHOP_URL=https://dev.eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3001"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.eshop-dev.rule=Host(`dev.eshop.badamigroups.com`)"
      - "traefik.http.routers.eshop-dev.entrypoints=websecure"
      - "traefik.http.routers.eshop-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.eshop-dev.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.eshop-dev-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.eshop-dev.middlewares=eshop-dev-headers"
      - "traefik.http.services.eshop-dev.loadbalancer.server.scheme=http"
      - "traefik.http.services.eshop-dev.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.eshop-dev.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net

  # Backend Development
  backend_dev:
    image: nurulhadii/zentra-api:dev
    container_name: zentra_backend_dev
    restart: always
    environment:
      - GIN_MODE=debug
      - POSTGRES_HOST=zentra_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB_DEV}
      - POSTGRES_USER=${POSTGRES_USER_DEV}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_DEV}
      - ELASTICSEARCH_HOSTS=http://zentra_elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET_DEV}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET_DEV}
      - SERVER_PORT=8080
      - CORS_ALLOWED_ORIGINS=https://dev.bisnisqu.badamigroups.com,https://dev.eshop.badamigroups.com
      - BACKUP_PATH=/backups
      - ENABLE_PUBLIC_HEALTH=true
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/public/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    volumes:
      - ${REMOTE_PATH}/uploads:/app/uploads
      - ${REMOTE_PATH}/backups/dev:/backups
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.backend-dev.rule=Host(`dev.zentra.badamigroups.com`)"
      - "traefik.http.routers.backend-dev.entrypoints=websecure"
      - "traefik.http.routers.backend-dev.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-dev.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.backend-dev-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.backend-dev-cors.headers.accesscontrolallowmethods=GET,POST,PUT,DELETE,OPTIONS"
      - "traefik.http.middlewares.backend-dev-cors.headers.accesscontrolallowheaders=*"
      - "traefik.http.middlewares.backend-dev-cors.headers.accesscontrolalloworiginlist=https://dev.bisnisqu.badamigroups.com,https://dev.eshop.badamigroups.com"
      - "traefik.http.middlewares.backend-dev-cors.headers.accesscontrolmaxage=100"
      - "traefik.http.middlewares.backend-dev-cors.headers.addvaryheader=true"
      - "traefik.http.routers.backend-dev.middlewares=backend-dev-headers,backend-dev-cors"
      - "traefik.http.services.backend-dev.loadbalancer.server.scheme=http"
      - "traefik.http.services.backend-dev.loadbalancer.healthcheck.path=/api/public/health"
      - "traefik.http.services.backend-dev.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net
      - backend-net
    depends_on:
      - postgres

  # Staging Environment
  frontend_staging:
    image: nurulhadii/zentra-ui:staging
    container_name: frontend_staging
    restart: always
    environment:
      - NODE_ENV=staging
      - PORT=3000
      - API_URL=https://staging.zentra.badamigroups.com
      - ESHOP_URL=https://staging.eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.frontend-staging.rule=Host(`staging.bisnisqu.badamigroups.com`)"
      - "traefik.http.routers.frontend-staging.entrypoints=websecure"
      - "traefik.http.routers.frontend-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend-staging.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.frontend-staging-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend-staging.middlewares=frontend-staging-headers"
      - "traefik.http.services.frontend-staging.loadbalancer.server.scheme=http"
      - "traefik.http.services.frontend-staging.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.frontend-staging.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net

  eshop_staging:
    image: nurulhadii/zentra-eshop:staging
    container_name: eshop_staging
    restart: always
    environment:
      - NODE_ENV=staging
      - PORT=3001
      - API_URL=https://staging.zentra.badamigroups.com
      - ESHOP_URL=https://staging.eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3001"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3001"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.eshop-staging.rule=Host(`staging.eshop.badamigroups.com`)"
      - "traefik.http.routers.eshop-staging.entrypoints=websecure"
      - "traefik.http.routers.eshop-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.eshop-staging.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.eshop-staging-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.eshop-staging.middlewares=eshop-staging-headers"
      - "traefik.http.services.eshop-staging.loadbalancer.server.scheme=http"
      - "traefik.http.services.eshop-staging.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.eshop-staging.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net

  # Backend Staging
  backend_staging:
    image: nurulhadii/zentra-api:staging
    container_name: zentra_backend_staging
    restart: always
    environment:
      - GIN_MODE=release
      - POSTGRES_HOST=zentra_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB_STAGING}
      - POSTGRES_USER=${POSTGRES_USER_STAGING}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_STAGING}
      - ELASTICSEARCH_HOSTS=http://zentra_elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET_STAGING}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET_STAGING}
      - SERVER_PORT=8080
      - BACKUP_PATH=/backups
      - ENABLE_PUBLIC_HEALTH=true
    volumes:
      - ${REMOTE_PATH}/uploads:/app/uploads
      - ${REMOTE_PATH}/backups/staging:/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-staging.rule=Host(`staging.zentra.badamigroups.com`)"
      - "traefik.http.routers.backend-staging.entrypoints=websecure"
      - "traefik.http.routers.backend-staging.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-staging.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.backend-staging-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.backend-staging.middlewares=backend-staging-headers"
      - "traefik.http.services.backend-staging.loadbalancer.server.scheme=http"
      - "traefik.http.services.backend-staging.loadbalancer.healthcheck.path=/api/public/health"
      - "traefik.http.services.backend-staging.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net
      - backend-net
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/public/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Production Environment
  frontend_prod:
    image: nurulhadii/zentra-ui:prod
    container_name: frontend_prod
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
      - API_URL=https://zentra.badamigroups.com
      - ESHOP_URL=https://eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3000"
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.frontend-prod.rule=Host(`bisnisqu.badamigroups.com`)"
      - "traefik.http.routers.frontend-prod.entrypoints=websecure"
      - "traefik.http.routers.frontend-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.frontend-prod.loadbalancer.server.port=3000"
      - "traefik.http.middlewares.frontend-prod-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.frontend-prod.middlewares=frontend-prod-headers"
      - "traefik.http.services.frontend-prod.loadbalancer.server.scheme=http"
      - "traefik.http.services.frontend-prod.loadbalancer.healthcheck.path=/"
      - "traefik.http.services.frontend-prod.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net

  # E-shop Production
  eshop_prod:
    image: nurulhadii/zentra-eshop:prod
    container_name: eshop_prod
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3001
      - API_URL=https://zentra.badamigroups.com
      - ESHOP_URL=https://eshop.badamigroups.com
      - PGADMIN_URL=https://pgadmin.badamigroups.com
    expose:
      - "3001"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.eshop.rule=Host(`eshop.badamigroups.com`)"
      - "traefik.http.routers.eshop.entrypoints=websecure"
      - "traefik.http.routers.eshop.tls.certresolver=letsencrypt"
      - "traefik.http.services.eshop.loadbalancer.server.port=3001"
      - "traefik.http.middlewares.eshop-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.middlewares.eshop-headers.headers.customrequestheaders.X-Real-IP=/"
      - "traefik.http.middlewares.eshop-headers.headers.customrequestheaders.X-Forwarded-Host=eshop.badamigroups.com"
      - "traefik.http.routers.eshop.middlewares=eshop-headers"
    networks:
      - traefik-net

  # Backend Production
  backend_prod:
    image: nurulhadii/zentra-api:prod
    container_name: zentra_backend_prod
    restart: always
    environment:
      - GIN_MODE=release
      - POSTGRES_HOST=zentra_postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=${POSTGRES_DB_PROD}
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - ELASTICSEARCH_HOSTS=http://zentra_elasticsearch:9200
      - JWT_SECRET=${JWT_SECRET_PROD}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET_PROD}
      - SERVER_PORT=8080
      - BACKUP_PATH=/backups
      - ENABLE_PUBLIC_HEALTH=true
    volumes:
      - ${REMOTE_PATH}/uploads:/app/uploads
      - ${REMOTE_PATH}/backups/prod:/backups
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend-prod.rule=Host(`zentra.badamigroups.com`)"
      - "traefik.http.routers.backend-prod.entrypoints=websecure"
      - "traefik.http.routers.backend-prod.tls.certresolver=letsencrypt"
      - "traefik.http.services.backend-prod.loadbalancer.server.port=8080"
      - "traefik.http.middlewares.backend-prod-headers.headers.customrequestheaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.backend-prod.middlewares=backend-prod-headers"
      - "traefik.http.services.backend-prod.loadbalancer.server.scheme=http"
      - "traefik.http.services.backend-prod.loadbalancer.healthcheck.path=/api/public/health"
      - "traefik.http.services.backend-prod.loadbalancer.healthcheck.interval=10s"
    networks:
      - traefik-net
      - backend-net
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/public/health || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Centralized PostgreSQL
  postgres:
    image: postgres:15.4-alpine
    container_name: zentra_postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER_PROD}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD_PROD}
      - POSTGRES_DB=${POSTGRES_DB_PROD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER_PROD}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - backend-net

  # Single pgAdmin instance
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: always
    depends_on:
      - postgres
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_PROXY_X_FOR_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PROTO_COUNT: 1
      PGADMIN_CONFIG_PROXY_X_PORT_COUNT: 1
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: 10
      PGADMIN_CONFIG_FILE_LOG_LEVEL: 10
    ports:
      - "5050:80"
    networks:
      - backend-net
      - traefik-net
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.pgadmin.rule=Host(`pgadmin.badamigroups.com`)"
      - "traefik.http.routers.pgadmin.entrypoints=websecure"
      - "traefik.http.routers.pgadmin.tls.certresolver=letsencrypt"
      - "traefik.http.services.pgadmin.loadbalancer.server.port=80"
      - "traefik.http.middlewares.pgadmin-headers.headers.customRequestHeaders.X-Script-Name=/pgadmin"
      - "traefik.http.middlewares.pgadmin-headers.headers.customRequestHeaders.X-Scheme=https"
      - "traefik.http.middlewares.pgadmin-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"
      - "traefik.http.routers.pgadmin.middlewares=pgadmin-headers"

  # Shared Services
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: zentra_elasticsearch
    restart: always
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=zentra-cluster
      - network.host=0.0.0.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    networks:
      - traefik-net
      - backend-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.badamigroups.com`)"
      - "traefik.http.routers.elasticsearch.entrypoints=websecure"
      - "traefik.http.routers.elasticsearch.tls.certresolver=letsencrypt"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: zentra_kibana
    restart: always
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=kibana.badamigroups.com
      - SERVER_PUBLICBASEURL=https://kibana.badamigroups.com
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch
    networks:
      - traefik-net
      - backend-net
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik-net"
      - "traefik.http.routers.kibana.rule=Host(`kibana.badamigroups.com`)"
      - "traefik.http.routers.kibana.entrypoints=websecure"
      - "traefik.http.routers.kibana.tls.certresolver=letsencrypt"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

volumes:
  postgres_data:
  elasticsearch_data:

networks:
  traefik-net:
    external: true
  backend-net:
    external: true 