version: '3.8'

services:

  frontend:
    image: nurulhadii/zentra-ui:dev
    container_name: frontend_local
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
      - PORT=3000
      - API_URL=http://localhost:8080/api
      - ESHOP_URL=http://localhost:3001
      - PGADMIN_URL=http://localhost:5050

  eshop:
    image: nurulhadii/zentra-eshop:dev
    container_name: eshop_local
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
      - PORT=3001
      - API_URL=http://localhost:8080/api
      - ESHOP_URL=http://localhost:3001
      - PGADMIN_URL=http://localhost:5050

  postgres:
    image: postgres:15.4-alpine
    container_name: zentra_postgres_local
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=zentra_dev
      - POSTGRES_PASSWORD=zentra_dev
      - POSTGRES_DB=zentra_dev
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U zentra_dev -d zentra_dev"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin_local
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@local.dev
      PGADMIN_DEFAULT_PASSWORD: admin
    depends_on:
      - postgres

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.7.0
    container_name: zentra_elasticsearch_local
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.name=zentra-local
      - network.host=0.0.0.0
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data

  kibana:
    image: docker.elastic.co/kibana/kibana:8.7.0
    container_name: zentra_kibana_local
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - SERVER_NAME=localhost
      - SERVER_HOST=0.0.0.0
    depends_on:
      - elasticsearch

volumes:
  postgres_data:
  elasticsearch_data: 